[pytest]

addopts = -s -v

python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    courses: Тестирование сервисов курсов
    dashboard: Тесты страницы Dashboard
    regression: Регрессионные тест
    registration: Тесты регистрации пользователя
    authorization: Тесты авторизации
