from enum import Enum



class AllureTags(str, Enum):
    COURSES = "COURSES"
    DASHBOARD = "DASHBOARD"
    REGRESSION = "REGRESSION"
    USER_LOGIN = "USERLOGIN"
    NAVIGATION = "NOVIGATION"
    REGISTRATION = "REGISTRATION"
    AUTHORISATION = "AUTHORIZATION"